- name: Install prerequisite packages
  yum:
    name:
      - curl
      - gnupg2
    state: present
  become: true

- name: Enable nodejs16
  command: amazon-linux-extras enable nodejs16
  become: true

- name: Clean yum metadata
  command: yum clean metadata
  become: true



- name: Install Node.js
  yum:
    name: nodejs
    state: present
  become: true

- name: Verify Node.js installation
  command: node --version
  register: node_version_output
  changed_when: false

- name: Show installed Node.js version
  debug:
    msg: "Node.js installed: {{ node_version_output.stdout }}"

- name: Verify npm installation
  command: npm --version
  register: npm_version_output
  changed_when: false

- name: Show installed npm version
  debug:
    msg: "npm installed: {{ npm_version_output.stdout }}"