---

- name: Install base packages
  apt:
    name:
      - python3
      - python3-pip
      - ca-certificates
      - curl
    state: present
    update_cache: true


- name: Install Docker prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: true


- name: Install ONLY system Docker Python binding
  apt:
    name: python3-docker
    state: present


- name: Create Jenkins home directory
  file:
    path: "{{ jenkins_home_host_path }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Run Jenkins controller container
  community.docker.docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ jenkins_http_port }}:8080"
      - "{{ jenkins_agent_port }}:50000"
    volumes:
      - "{{ jenkins_home_host_path }}:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock


- name: Wait for Jenkins to start
  uri:
    url: "http://localhost:{{ jenkins_http_port }}/login"
    status_code: 200
  register: result
  retries: 30
  delay: 10
  until: result.status == 200



- name: Get Jenkins initial admin password
  command: docker exec {{ jenkins_container_name }} cat /var/jenkins_home/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Show Jenkins password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"

- name: Generate SSH keypair for Jenkins agents
  openssh_keypair:
    path: /home/ubuntu/.ssh/jenkins_agent_key
    type: rsa
    size: 4096
    owner: ubuntu
    group: ubuntu
  become: true
  register: jenkins_agent_keypair

- name: Fetch public key locally
  fetch:
    src: /home/ubuntu/.ssh/jenkins_agent_key.pub
    dest: "{{ playbook_dir }}/../generated/jenkins_agent_key.pub"
    flat: true
  become: true